[server]
# Configuraci贸n para deployment
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Configuraci贸n del navegador
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
# Tema oficial de Allianz
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#003366"
font = "sans serif"

[logger]
# Configuraci贸n de logging
level = "info"

[client]
# Configuraci贸n del cliente
showErrorDetails = true 