[server]
# Configuraci贸n para deployment
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Configuraci贸n del navegador
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
# Tema personalizado para Allianz
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[logger]
# Configuraci贸n de logging
level = "info"

[client]
# Configuraci贸n del cliente
caching = true
showErrorDetails = true 